from . import department
from . import teacher
from . import student
from . import subject
from . import classroom
from . import enrollment
from . import grade
from . import attendance
from . import schedule
from . import dashboard
from . import ai_assistant
from . import ai_service
from . import ai_settings